# action.yml
name: 'Toot It'
description: 'Send any unsent toots from a specified inbox'
branding:
  icon: send
  color: blue
inputs:
  inbox:
    description: 'Path to a folder of markdown documents to toot'
    required: true
    default: 'inbox'
  outbox:
    description: 'Where would you like these documents saved'
    required: true
    default: 'outbox'
  server:
    description: 'Server name (e.g. mastodon.social)'
    required: true
    default: 'mstdn.science'
  toot_length:
    description: 'Maximum characters in your servers toots'
    required: true
    default: '500'
  token:
    description: 'Access token token (you must create your own app to toot as you.)'
    required: true
    default: 'not-a-real-token'
  file:
    description: 'Toot a specific markdown document (will ignore inbox/outbox)'
    required: false
    default: does-not-exist.md
  visibility:
    description: 'Set the visibility for a toot (only if using file to toot a specific file.)'
    required: true
    default: 'private'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.inbox }}
    - ${{ inputs.outbox }}
    - ${{ inputs.server }}
    - ${{ inputs.token }}
    - --file
    - ${{ inputs.file }}
    - --toot-length
    - ${{ inputs.toot_length }}
    - --visibility 
    - ${{ inputs.visibility }}
